# Generated by Django 4.1.13 on 2024-04-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_user_alter_product_url_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=600, unique=True),
        ),
    ]
